# Generated by Django 4.1.3 on 2022-11-05 10:17

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_homepage_applets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="applets",
            field=wagtail.fields.StreamField(
                [
                    (
                        "button_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                ("description", wagtail.blocks.CharBlock()),
                                ("url", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    ),
                    (
                        "contact_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                ("email", wagtail.blocks.EmailBlock()),
                            ]
                        ),
                    ),
                    (
                        "notes_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "notes",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("title", wagtail.blocks.CharBlock()),
                                                (
                                                    "content",
                                                    wagtail.blocks.RichTextBlock(
                                                        features=[
                                                            "h2",
                                                            "bold",
                                                            "italic",
                                                            "link",
                                                        ]
                                                    ),
                                                ),
                                            ],
                                            label="notes",
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "pomodoro_applet",
                        wagtail.blocks.StructBlock(
                            [("title", wagtail.blocks.CharBlock(max_length=20))]
                        ),
                    ),
                    (
                        "social_links_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("title", wagtail.blocks.CharBlock()),
                                                ("url", wagtail.blocks.URLBlock()),
                                            ],
                                            label="links",
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "testimonies_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "testimonies",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("quote", wagtail.blocks.CharBlock()),
                                                (
                                                    "photo",
                                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                                ),
                                                ("name", wagtail.blocks.CharBlock()),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                            ],
                                            label="testimonies",
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "textual_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h2", "bold", "italic", "link"]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "timeline_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "events",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("date", wagtail.blocks.DateBlock()),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=20
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(),
                                                ),
                                            ],
                                            label="events",
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "todo_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "tasks",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.CharBlock(), label="tasks"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_applet",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=20)),
                                (
                                    "media",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
